### PR TITLE
Ensure that Python 2 is found and used

### PR DESCRIPTION
**Pull request by JP-Ellis**
When finding the Python interpreter, specify that version 2 *must* be found and also make sure that the Python libraries are found matching the Python interpreter.

Note that this commit does not fix hard-coded references to `python` outside of the CMake scripts.  Executable files with `#!/usr/bin/python` disregard which Python interpreter was found by CMake.

This pull request can be updated if `.py` scripts should make use of the Python interpreter found by CMake.

### CODE REVIEW

**Comment by patscott** [comment]
Thanks Joshua - I've pulled this into the development fork, and it will appear in the next release.  

I had to change the Python version detection as follows:

```
# Check for Python and required libs
find_package(PythonInterp 2 REQUIRED)
if (PYTHON_VERSION_MAJOR GREATER 2)
  message(FATAL_ERROR "GAMBIT requires Python 2")
endif()
```

as otherwise it demands exactly 2.7, which fails for 2.7.* on my system.  I suspect this is probably because I'm running cmake 2.8.12 and you're running 3.0 or later.

**Comment by JP-Ellis** [comment]
It's a shame that CMake 2.8 behaves differently (then again, the last update to CMake 2.8 was 4 years ago, so it's understandable that they have diverged).

With CMake 3, `find_package(PythonInterp 2 REQUIRED)` finds Python 3 even if Python 2 is also available which is not the intended behaviour; so your change will still not work.  You also fail to check whether Python is at least version 2.7 (seeing as the GAMBIT code won't work with Python 2.6).

If you specify `find_package(PythonInterp 2 EXACT REQUIRED)` does it work in CMake 2?  The behaviour describes in [CMake 2's documentation is not entirely clear](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:find_package).

**Comment by patscott** [comment]
```EXACT REQUIRED``` in cmake 2 looks for a version string that matches exactly what you give, so no, no usage of that works.

We tested the new code with different versions of cmake 3, it works.  The behaviour you describe is what the if block is there to deal with.

We haven't tested with Python 2.6, so we don't actually know how low GAMBIT can go within the 2.* family, that's why we don't preclude the usage of earlier versions.  Have you tested with 2.6 or earlier and seen it fail?

**Comment by JP-Ellis** [comment]
I haven't formally tested if it works with Python 2.6; however, while having a quick look at the code I saw a `print` function which, if I recall correctly, was only introduced in Python 2.7 (prior to that, there is only the `print` statement).

Also with regards to the change.  Perhaps I wasn't clear.  The line

```
find_package(PythonInterp 2.7 EXACT REQUIRED)
```

in CMake 3 will ensure that Python 2 is found *even if Python 3 is also there*.  On the other hand,

```
find_package(PythonInterp 2.7 REQUIRED)
```

might either find Python 3 or Python 2 if both are installed (I'm not sure whether it prioritizes new versions or not, if it does then the issue is even worse).  If both Python 2 and Python 3 are installed, then CMake may not find Python 2 even though it is installed, and then CMake will return an error despite Python 2 being available.

Is it possible in CMake 2 to specify manually the exact `VERSION_MAJOR` variable?  If that isn't possible, then perhaps it might be worth either trying to find Python 2 manually, or inform the user that a path to the Python interpreter can be manually specified with

```
-DPYTHON_EXECUTABLE:FILEPATH=/path/to/python2.7
```

**Comment by patscott** [comment]
Actually it seems that we do support Python 2.6 in the build stage, as one of our continuous integration builds uses this (SLC6 -- which we do need to support).  The only place where we use the print function is in a deprecated runtime script that we left in there for cross-checking against the C++ equivalent.  I've now made that use the print statement instead as well.  So, I'm going to leave the permissive 2.* requirement, unless someone indicates that they have seen the build fail with some specific older version.

At least on my system, which has both Python 2 and Python 3 installed, the code I pasted above successfully prefers v2 over v3.  Setting ```PYTHON_VERSION_MAJOR``` has no impact in CMake 2.  To catch any cases where CMake behaves differently to my system, and chooses Python 3 over Python 2 where they both exist, I've therefore also modified the error message to tell the user that they can set ```-DPYTHON_EXECUTABLE:FILEPATH=path/to/preferred/python``` if they want to do things manually.

In general, looking at related issues raised for other codes, it seems detection of Python versions by CMake on systems with multiple Python installations is bit of a buggy can of worms, not yet resolved upstream.  So I think this is the best that can be done, and should catch 99.9% of use cases.  If someone runs into a use case where this system breaks, please raise a new issue.

Thanks for the feedback Joshua.

**Pull request closed without merging**
